# Generated by Django 4.0.2 on 2022-02-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%y/%m/%d/'),
        ),
    ]
